  
name: 'Tests'

on:
  push:

  pull_request:
    types: [opened, synchronize] #labeled, assigned]

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            python-version: 3.7
            python: xvfb-run python3
            pip_arg: ""
          - os: ubuntu-18.04
            python-version: 3.8
            python: xvfb-run python3
            pip_arg: ""
          - os: ubuntu-18.04
            python-version: 3.9
            python: xvfb-run python3
            pip_arg: ""
          - os: macos-10.15
            python-version: 3.7
            python: python3
            pip_arg: ""
          - os: macos-10.15
            python-version: 3.8
            python: python3
            pip_arg: ""
          - os: macos-10.15
            python-version: 3.9
            python: python3
            pip_arg: ""
          - os: windows-2019
            python-version: 3.7
            python: python
            pip_arg: --user
          - os: windows-2019
            python-version: 3.8
            python: python
            pip_arg: --user
          - os: windows-2019
            python-version: 3.9
            python: python
            pip_arg: --user
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install -e .
          python -m unittest discover -v
      - name: Make run
        run: |
          make singletest
